model:
  name: "yolov3"
  n_classes: 1
  class_names: "custom_classes.txt"
  ignore_threshold: 0.7
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_mask: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
train:
  img_size: 608
  lr: 0.001
  burn_in: 1000
  steps: [8000, 9000]
  momentum: 0.9
  decay: 0.0005
  max_iter: 10000
  batch_size: 4
  subdivision: 16
augmentation:
  random_size: True
  lr_flip: True
  distortion: True
  random_placing: True
  jitter: 0.3
test:
  batch_size: 32
  conf_threshold: 0.5
  nms_threshold: 0.45
  img_size: 416
